### ISSUE TITLE
Eloquent/ORM panel tab does not display total time 

### ISSUE THREAD

**Issue by innobrig** [runcmf/runtracy#2]
The Database (Eloquent) panel tab does not display the total time spent on SQL queries, it only display an entry like this: 

    [icon] 1 / ms

To  clarify, after the "/" it does not print the actual time spent, it only prints "ms". 

Other than that, this is a wonderful addition for slim developers, thanks a lot for providing it!

**Comment by 1f7** [comment]
@innobrig 
thank you very much!
up to **0.2.5**
run `composer update`
