### ISSUE TITLE
Dead project or is support for slim 4.5 in planning ?

### ISSUE THREAD

**Issue by snoopy72** [runcmf/runtracy#20]
Due to the date of last changes (somewhere in 2017) i think, this project is dead.

It it not usable any more in slim 4.5 and had to be removed.

Pitty, because this tool was helpful sometimes.

**Comment by odan** [comment]
Not sure if it helps, but have you tried using XDebug? XDebug also provides a very good [profiler](https://xdebug.org/docs/profiler) and works great in combination with [PhpStorm](https://www.jetbrains.com/help/phpstorm/configuring-xdebug.html). 

[XDebug Setup](https://gist.github.com/odan/1abe76d373a9cbb15bed)
