### ISSUE TITLE
Error displayed in browser/JS console

### ISSUE THREAD

**Issue by innobrig** [runcmf/runtracy#3]
Using the latest version, the following error is displayed in the browser/JS console: 

    ?_tracy_bar=js&v=2.4.4&XDEBUG_SESSION_STOP=1:317 Error: <path> attribute d: Expected number, "…310.303V325.818h46.\n            …".

**Comment by 1f7** [comment]
@innobrig
 `<path>` used in `jquery.terminal.min.js`
check in browser/console/Network Monitor - maybe error loading jquery.terminal.min.js

**Comment by innobrig** [comment]
Sorry for not getting back to you earlier ... you are correct that loading jquery.terminal.min.js solves the error.

**Comment by jimblue** [comment]
Hello, Im getting this error in the google chrome inspector:

```
Error: <path> attribute d: Expected number, "…310.303V325.818h46.\n            …".
Debug.init @ ?_tracy_bar=content.8963797ac3&XDEBUG_SESSION_STOP=1:315
(anonymous) @ ?_tracy_bar=content.8963797ac3&XDEBUG_SESSION_STOP=1:882
````

What should I do?

**Comment by 1f7** [comment]
Hi @jimblue,
you should read my answer above.
`<path>` used **ONLY** in `jquery.terminal.min.js`
or off terminal or correct path and check `jquery.terminal.min.js` is loaded successfully

**Comment by jimblue** [comment]
Hi @1f7 ,

Thanks for your rapid answer.

But I don't have error about loading "jquery.terminal.min.js".

The error I post in my last message is the only one I get.

Maybe I'm doing something wrong, but don't know where?

**Comment by 1f7** [comment]
Hi @jimblue,
You not forget add jquery?
For help you, I need reproduce error, but how?
If site available from i-net I can look at.

**Comment by jimblue** [comment]
Hi @1f7 ,

I've try to deactivate all option then activate them 1 by 1.

The console error pop up only for 2 module:

- Vendor versions panel
- Console

Sorry I'm working only on local for now.

**Comment by 1f7** [comment]
I found error. this is from `svg` image path.
In nearest time I will update repo
@jimblue thank you.

**Comment by jimblue** [comment]
@1f7 indeed !! It's working now, thank you :)

**Comment by jimblue** [comment]
Hi @1f7 !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by 1f7** [comment]
ready
