### ISSUE TITLE
Doctrine

### ISSUE THREAD

**Issue by ChoiZ** [runcmf/runtracy#4]
Is it planed to add doctrine ORM?

**Comment by 1f7** [comment]
sure, but a little later.
now play with idiorm, and following for sure doctrine

**Comment by ChoiZ** [comment]
Ok thanks for the answer! ;-)

**Comment by 1f7** [comment]
Idiorm and Doctrine DBAL ready

**Comment by 1f7** [comment]
added Doctrine collector for both DBAL and ORM

**Comment by ChoiZ** [comment]
👍 Nice!

**Comment by Fukotaku** [comment]
I'm applying runtracy with my slim project using doctrine, everything works except doctrine/dbal.
I launch `$this->em->getRepository('App\Entity\User')->findAll();` on my controller and tracy return 'No Logs, maybe own collector work?'

an idea?
