### ISSUE TITLE
Reference error in version 0.2.6

### ISSUE THREAD

**Issue by innobrig** [runcmf/runtracy#5]
I get the following error (actually, a PHP warning) in version 0.2.6: 

    PHP Notice: Undefined index: showIdiormPanel in .../src/RunTracy/Middlewares/TracyMiddleware.php:161

I tried selecting/deselecting all options/panels but the error remains. Looking at the code, it seems like an isset() check is missing on line 161. 

Other that that, once again thanks for a great package!

**Comment by 1f7** [comment]
@innobrig
fixed. also add some test.
many thanks.

I update package today
