### ISSUE TITLE
Unable to get the panel displaying 

### ISSUE THREAD

**Issue by NigelGreenway** [runcmf/runtracy#6]
I might be doing something stupid here, but I can not get the panel to render in the HTML?

Should this render the panel automatically or should I be explicitly adding some HTML within Twig to render it or call a function?

**Comment by NigelGreenway** [comment]
Ignore that, I passed the wrong value to something :(

**Comment by 1f7** [comment]
No problem.
the main thing you have found a solution.

Do not need touch templates, Tracy append after `</body></html>`.
For show Tracy you only need enable `Debugger::enable();`
this minimum you must see Tracy panel.
all other is Tracy addons.

**Comment by arma7x** [comment]
@1f7 Debugger::enable(); does not works for me. Already follow the guide, but panel didn't render

**Comment by arma7x** [comment]
Already fix, by 'addContentLengthHeader' => false,

**Comment by 1f7** [comment]
@arma7x, thanks i add it in readme
