### ISSUE TITLE
Runtracy doesn't work with PHP-DI as container

### ISSUE THREAD

**Issue by llvdl** [runcmf/runtracy#7]
Runtracy does not currently work when using PHP-DI as the container in a Slim application using the [PHP-DI Slim bridge](https://github.com/PHP-DI/Slim-Bridge).

Runtracy assumes that the container has array access, which the default Slim Container provides, but are not part of the Container Interop interface.

**Comment by 1f7** [comment]
@llvdl today I do not use PHP-DI and this did not test him.
Thank you very much!

**Comment by llvdl** [comment]
Thanks for merging :smiley:
